name: Create Daily README

permissions:
  contents: write

on:
  schedule:
    - cron: '0 21 * * 0-4' # 한국 시간 오전 6시 = UTC 21시, 일~목 (즉 월~금 오전 6시)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run create_day_md.py script #.github/scripts/create_day_md.py
        run: python .github/scripts/create_day_md.py 

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "자동 생성된 README.md 추가" || echo "No changes to commit"
          git push
